# Generated by Django 6.0.5 on 2026-05-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
